import { z } from "zod";

export const industryTypes = [
  { value: "restaurant", label: "Restaurante" },
  { value: "cafe", label: "Cafetería" },
  { value: "bakery", label: "Panadería" },
  { value: "pastry_shop", label: "Pastelería" },
  { value: "ice_cream_shop", label: "Heladería" },
  { value: "jewelry", label: "Joyería" },
  { value: "barbershop", label: "Barbería" },
  { value: "hair_salon", label: "Peluquería" },
  { value: "makeup_store", label: "Tienda de maquillaje" },
  { value: "beauty_salon", label: "Spa / Salón de belleza" },
  { value: "aesthetic_center", label: "Centro estético" },
  { value: "workshop", label: "Taller" },
  { value: "clothing_store", label: "Tienda de ropa" },
  { value: "accessories_store", label: "Tienda de accesorios de moda" },
  { value: "phone_store", label: "Tienda de celulares" },
  { value: "computer_store", label: "Tienda de computadores" },
  { value: "appliance_store", label: "Tienda de electrodomésticos" },
  { value: "tech_store", label: "Tienda de tecnología" },
  { value: "pet_store", label: "Tienda de mascotas" },
  { value: "home_decor_store", label: "Tienda de decoración para el hogar" },
  { value: "flower_store", label: "Floristería" },
  { value: "toy_store", label: "Juguetería" },
  { value: "sporting_goods_store", label: "Tienda de artículos deportivos" },
  { value: "stationery_store", label: "Papelería" },
  { value: "bookstore", label: "Librería" },
  { value: "hardware_store", label: "Ferretería" },
  { value: "hair_supply_store", label: "Tienda de insumos para peluqueros" },
  { value: "optical_store", label: "Óptica" },
  { value: "online_store", label: "Tienda virtual (redes sociales)" },
  { value: "gym", label: "Gimnasio" },
  { value: "veterinary_clinic", label: "Veterinaria" },
  { value: "dental_clinic", label: "Consultorio odontológico" },
  { value: "car_dealership", label: "Concesionario" },
  { value: "real_estate_agency", label: "Inmobiliaria" },
  { value: "vacation_rental", label: "Alquiler vacacional (apartamentos, fincas, Airbnb)" },
  { value: "construction_company", label: "Constructora" },
  { value: "travel_agency", label: "Agencia de viajes" },
  { value: "event_planning", label: "Organización de eventos" },
  { value: "photo_video_studio", label: "Estudio de fotografía y video" },
  { value: "tattoo_studio", label: "Estudio de tatuajes" },
  { value: "personal_brand", label: "Marca personal" },
] as const;

export const businessSchema = z.object({
  name: z
    .string()
    .min(2, "El nombre debe tener al menos 2 caracteres")
    .max(100),
  industry_type: z.enum([
    "restaurant",
    "cafe",
    "bakery",
    "pastry_shop",
    "ice_cream_shop",
    "jewelry",
    "barbershop",
    "hair_salon",
    "makeup_store",
    "beauty_salon",
    "aesthetic_center",
    "workshop",
    "clothing_store",
    "accessories_store",
    "phone_store",
    "computer_store",
    "appliance_store",
    "tech_store",
    "pet_store",
    "home_decor_store",
    "flower_store",
    "toy_store",
    "sporting_goods_store",
    "stationery_store",
    "bookstore",
    "hardware_store",
    "hair_supply_store",
    "optical_store",
    "online_store",
    "gym",
    "veterinary_clinic",
    "dental_clinic",
    "car_dealership",
    "real_estate_agency",
    "vacation_rental",
    "construction_company",
    "travel_agency",
    "event_planning",
    "photo_video_studio",
    "tattoo_studio",
    "personal_brand",
  ]),
});

export type BusinessInput = z.infer<typeof businessSchema>;
